### ISSUE TITLE
On map: Refine drag interaction

### ISSUE THREAD

**Issue by SundayFunday** [CodeForCharlotte/adopt_a_node#42]

**Comment by tannerhodges** [comment]
See Google Maps' “Drag to change route” feature as a reference.

More on this from @rmion

**Comment by rmion** [comment]
Perhaps this will help guide functionality towards a better UX:
Adopters are not likely to draw paths on the map in order to select their desired street(s). Instead, when presented with clear indicators of what streets are eligible, pending adoption or ineligible, adopters will click on the portion of the street closest to their business or home or to the scene of a memorable event.

The current application captures only the amount of selected street between the nearest intersections, which is not exactly expected behavior, especially if the amount of eligible street continues passed an intersection.

So suggested functionality may involve allowing the adopter to perform the initial selection, and then drag that selection's endpoints to encompass more or less of the total eligible area of the selected street.
